# Generated by Django 4.0.5 on 2022-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('desde', models.IntegerField()),
                ('hasta', models.CharField(max_length=50)),
                ('tareas_1', models.CharField(max_length=100)),
                ('tareas_2', models.CharField(max_length=100)),
                ('tareas_3', models.CharField(max_length=100)),
                ('tareas_4', models.CharField(max_length=100)),
                ('tareas_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=50)),
                ('anio_recibido', models.IntegerField()),
            ],
        ),
    ]
