# Generated by Django 4.0.5 on 2022-07-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_alter_experiencia_desde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
