# Generated by Django 4.0.5 on 2022-07-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_delete_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacion',
            old_name='anio_recibido',
            new_name='año_recibido',
        ),
    ]
